# services.yaml

parameters:
 

services:

    _defaults:
        autowire: true     
        autoconfigure: true 

    # Cette règle permet à Symfony de charger automatiquement les classes sous le namespace App\ (dans le dossier src/)
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/*'
            - '../src/Entity/*'           
            - '../src/Kernel.php'             

    # Exemple de service explicite si nécessaire (optionnel)
    # App\Controller\TaskCreateController:
    #    arguments: ['@some_other_service']
